#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/.config
. /lib/livekitlib

transfer_initramfs

MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles

header "Maigc live start <http://www.magiclinux.org/>"

init_proc_sysfs

debug_start

init_scsi                                                                                                                                                      debug_shell
init_usbstorage
sleep 3
init_devs
init_nls
init_isofs
init_vfat
init_aufs
init_zram

# modprobe all devices excluding network drivers
modprobe_everything -v /drivers/net/

# initialize blkid cache file
init_blkid_cache

# find data dir with filesystem bundles
DATA="$(find_data 45 "$DATAMNT")"
check_data_found "$DATA"

                                                                                                                                                      debug_shell
# setup persistent changes, if possible
persistent_changes "$DATA" "$CHANGES"
                                                                                                                                                      debug_shell
# copy to RAM if needed
DATA="$(copy_to_ram "$DATA" "$CHANGES")"
                                                                                                                                                      debug_shell

# mount bundles
mount_bundles "$DATA" "$BUNDLES"
                                                                                                                                                      debug_shell																		   
# init aufs union, or setup overlayfs union
init_union "$CHANGES" "$UNION" "$BUNDLES"
                                                                                                                                                      debug_shell
# add data to union
union_append_bundles "$BUNDLES" "$UNION"
                                                                                                                                                      debug_shell
# rootcopy
copy_rootcopy_content "$DATA" "$UNION"

# create fstab
fstab_create "$UNION" "$DATAMNT"
                                                                                                                                                      debug_shell
# run user custom preinit
user_preinit "$DATA" "$UNION"

header "Live Kit done, starting $LIVEKITNAME"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
